<!-- Footer -->
<div id="footer" class="container_3">
	<div class="divider grid_3"></div>
	<div class="grid_1">
		<span class="large">So what's the story?</span><br />
		Drop us a line, we'd love to hear from you.<br />
		<a href="mailto:Hello@CitizenRacecar.com">Hello@CitizenRacecar.com</a> <BR />
        (718) 440-9434
	</div>
	<img src="img/CRRacecar.svg" />
</div>
<div id="footer2" class="container_3">
	&copy;2013 CitizenRacecar. All rights reserved.
</div>