<!-- Header -->
<div id="header" class="container_full">
	<div id="headerbackground"></div>
	<div id="logo"><a href="index.php" title="CitizenRacecar"><img src="img/CRLogotype.svg" /></a></div>
	<div id="tagline">We tell stories.</div>
	<div class="socialcontainer">
        <div class="socialbutton"><a class="pinterest" href="http://pinterest.com/citizenracecar" target="_blank">Pinterest</a></div>
        <div class="socialbutton"><a class="vimeo" href="https://vimeo.com/citizenracecar" target="_blank">Vimeo</a></div>
        <div class="socialbutton"><a class="twitter" href="https://twitter.com/CitizenRacecar" target="_blank">Twitter</a></div>
        <div class="socialbutton"><a class="linkedin" href="http://www.linkedin.com/company/citizenracecar/" target="_blank">LinkedIn</a></div>
        <div class="socialbutton"><a class="facebook" href="https://www.facebook.com/CitizenRacecar" target="_blank">Facebook</a></div>
    </div>

    <div id="navcontainer" class="container_3">
	    <div id="nav" class="grid_3">
			<div class="navbutton"><a id="work" href="index.php">WORK</a></div>
			<div class="divider">/</div>
	        <div class="navbutton"><a id="about" href="about.php">ABOUT</a></div>
	        <div id="prevproj"></div>
	        <div id="nextproj"></div>
		</div>
	</div>
</div>